### ISSUE TITLE
Server does not stop

### ISSUE THREAD

**Issue by justinbchen** [rtm516/MCXboxBroadcast#13]
I have Geyser+Floodgate+MCXboxBroadcastExtension on my server. When issuing the stop command (eg from Pterodactyl panel), the server hangs on the last console output and does not shut down unless the process is killed.

May be related to similar issues on Geyser/Floodgate that cause the same problem.

**Comment by rtm516** [comment]
Try updating to the latest Geyser build as this was fixed upstream so should be fixed here aswell

**Comment by justinbchen** [comment]
There have been attempted fixes, but the issue is still present: https://github.com/GeyserMC/Floodgate-Fabric/issues/59
