### ISSUE TITLE
MCXboxBroadcast Geyser Extension hangs server

### ISSUE THREAD

**Issue by Practor009** [rtm516/MCXboxBroadcast#81]
Hello everyone,  I am running a java fabric 1.20.6 server with  Geyser and Floodgate for  bedrock verification.

Please see geyser dump below:
https://dump.geysermc.org/shPe6qRbg1UAvsaNxioLFwLHNE7fRbhh

I tried installing the MCXboxBroadcast extension for Geyser to allow console players to connect, however, whenever the server is stopped, the shutdown gets stuck (see image) and hangs the whole process.
![Screenshot_2024-06-05_084754](https://github.com/rtm516/MCXboxBroadcast/assets/163452913/d348b281-2342-4521-a7dc-7955364c9e7c)

I have identified the issue is the MCxboxBroadcast extension because removing it, solves the problem. Additionally running Geyser in debug mode for logging produces the following console log, indicating that even though Geyser states to have disabled the extension on server stop, the extension is still running and preventing server shutdown.
![Screenshot_2024-06-05_103351](https://github.com/rtm516/MCXboxBroadcast/assets/163452913/a782b019-0703-4fc2-8aa3-a43771e816d2)

Having the server shut down successfully is important as it is managed through systemd and this behaviour will break all its scripts.

**Comment by rtm516** [comment]
Resolved in https://github.com/rtm516/MCXboxBroadcast/commit/84d2052e6a98360e549e712e33e11924603d047d

**Comment by Practor009** [comment]
Unfortunately still persists :/ not sure why the thread hangs the server terminal..

**Comment by rtm516** [comment]
This looks like a Geyser issue, tested on my own machine with a fabric setup and with or without the extension it hangs.

**Comment by Practor009** [comment]
After a review from the Geyser team on this issue thread: [https://github.com/GeyserMC/Geyser/issues/4778](url),
They insist this issue originates from the MCXboxBroadcast extension. After their suggestion, I am including a thread dump here to indicate which threads remain running after server stop command is issued:
[jvm.log](https://github.com/user-attachments/files/15919253/jvm.log)

**Comment by rtm516** [comment]
Interesting can you provide exact versions for fabric, geyser and floodgate?
I think a geyser dump has that you can provide 9!3

**Comment by Practor009** [comment]
Of course here is the Geyser dump: [https://dump.geysermc.org/DYzhC2DoOSdIVashEGK2r2bed8IDmfUB](url)

Also a list of all used mods and versions:

1. fabric-api-0.100.1+1.21.jar
2. ViaFabric-0.4.14+73-main.jar
3. ViaBackwards-5.0.0.jar
4. ViaRewind-4.0.0.jar
5. viewdistancefix-fabric-1.21-1.0.2.jar
6. spark-1.10.73-fabric.jar
7. lithium-fabric-mc1.21-0.12.5.jar
8. Geyser-Fabric.jar
9. Floodgate-Fabric-2.2.3-SNAPSHOT+build.28.jar

**Comment by rtm516** [comment]
Can you confirm this is still an issue on the latest Geyser + MCXboxBroadcast?

**Comment by Practor009** [comment]
Hello,
Yes, just updated to the extension Build 44 (Master) and latest Geyser version 2.4.1-b636 (git-master-83d8c19).
Issue still persists, if I remove the extension, problem goes away.

Can you also replicate on your end? Just to confirm this is not an issue of my hardware or any other OS config for example.

**Comment by rtm516** [comment]
Can you try build 45? I've made some improvements around shutdown and it seemed more reliable on my test server

**Comment by Practor009** [comment]
Yes! It looks like you fixed it, I made a clean reinstall of the extension. The first shutdown where I authenticated the account for bedrock still ended up hanging, but every reboot of the server after that shut down successfully.
Thank you so much.
